# Add labels to any any pull request with changes to the specified paths

# Pull requests that update GitHub Actions code. If you navigate to the folder, you will have a README of what it does
GitHub Actions:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'

postmortems:
- changed-files:
  - any-glob-to-any-file: 'docs/reports/**/*'

argilla:
- changed-files:
  - any-glob-to-any-file: 'docker/argilla/docker-compose.yml'

off2:
- changed-files:
  - any-glob-to-any-file: 'off2'

off1:
- changed-files:
  - any-glob-to-any-file: 'off1'

ovh2:
- changed-files:
  - any-glob-to-any-file: 'ovh2'

ovh3:
- changed-files:
  - any-glob-to-any-file: 'ovh3'

moji:
- changed-files:
  - any-glob-to-any-file: 'moji'
